### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by KruznickMeta** [noonesimg/obsidian-audio-player#2]
I've downloaded the file as mentioned via terminal and the folder is present in plugins but it's not showing up on my list.

**Comment by noonesimg** [comment]
make sure you followed these steps:
1. close obsidian
2. go to your vault .obsidian/plugins folder
3. git clone https://github.com/noonesimg/obsidian-audio-player.git
4. open obsidian
5. go to settings-> community plugins
6. scroll down, find "Audio Player" plugin and enable it

I'll update the README.md to make it less confusing.
