### ISSUE TITLE
Doesn't work with m4a

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [noonesimg/obsidian-audio-player#7]
It appears the player only works for mp3? Haven't tested mp4, but m4a doesn't work.

**Comment by profucius** [comment]
Here to report this too. I use m4a files which are exported from my Google Recorder app. I would use your plugin for listening to these files. Please add or fix support for m4a files thank you.

**Comment by blumpcus** [comment]
I would also appreciate this! Lots of recordings default to m4a, would be great to not have to convert them.
