### ISSUE TITLE
Modifies shell block in reader view

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [noonesimg/obsidian-audio-player#9]
The following code block
````
```shell
git push <remote> <branch> # standard push
git push <remote> --force # pushes even when it's a non-fast-forward merge
git push <remote> --all # push all branches to the remote
git push <remote> --tags # tags are not pushed automatically, this will push all tags
git push <remote> v1.0.1 # push an individual tag (v1.0.1 in this case)
```
````
Is rendered normally in edit mode, but for some reason this plugin causes it to be rendered with comments on separate lines in reader view:
![image](https://user-images.githubusercontent.com/31261158/213570577-d9ad7e33-d1f5-4686-b333-ce33d158d3dd.png)
Disabling this plugin fixes the formatting issue.

**Comment by geoffreysflaminglasersword** [comment]
Also, it seems the issue is only with `shell` blocks? I haven't tested exhaustively, but other languages  don't have the issue

**Comment by noonesimg** [comment]
Not sure what's going on here, seems like you've opened an issue in a wrong repo

**Comment by geoffreysflaminglasersword** [comment]
> Not sure what's going on here, seems like you've opened an issue in a wrong repo

This is the right repo, are you not able to reproduce this behavior? If I open a sandbox vault and install only obsidian-audio-player, this occurs. It does seem odd that the issue is related to this plugin, but it is definitely this plugin.
